# Generated by Django 3.0.5 on 2021-06-15 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# Generated by Django 3.0.5 on 2021-06-15 20:09

import django.contrib.auth.validators



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Придумайте краткое и ёмкое название категории произведений', max_length=200, verbose_name='название категории')),
                ('slug', models.SlugField(blank=True, help_text='Краткое, уникальное слово, которое будет видно в ссылке на страницу категории (часть URL)', max_length=100, null=True, verbose_name='url (slug)')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Категория',
                'db_table': 'categories_title',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Придумайте краткое и ёмкое название для жанра произведений', max_length=200, verbose_name='название жанра')),
                ('slug', models.SlugField(blank=True, help_text='Краткое, уникальное слово, которое будет видно в ссылке на страницу жанра (часть URL)', max_length=100, null=True, verbose_name='url (slug)')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'Жанр',
                'db_table': 'genres_title',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('year', models.DateTimeField(auto_now_add=True, verbose_name='Год публикации')),
                ('description', models.TextField(blank=True, help_text='Опишите жанр так, чтобы пользователь мог легко  определиться с выбором жанра для произведения.', null=True, verbose_name='описание')),
                ('category', models.ForeignKey(blank=True, help_text='Категория произведения.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_titles', to='api.Category', verbose_name='категория')),
                ('genre', models.ForeignKey(blank=True, help_text='Жанр произведения.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre_titles', to='api.Genre', verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'произведения',
                'db_table': 'titles_title',
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.SmallIntegerField(verbose_name=10)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Title')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'сообщения',
                'db_table': 'reviews_review',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('role', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
            ],
        )
    ]
