# Generated by Django 3.0.5 on 2021-06-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Год выпуска', null=True, verbose_name='Год выпуска'),
        ),
    ]
