# Generated by Django 3.0.5 on 2021-06-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date',), 'verbose_name': 'review', 'verbose_name_plural': 'отзывы'},
        ),
    ]
