# Generated by Django 3.0.5 on 2021-06-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите категорию произведения.', max_length=200, unique=True, verbose_name='Категория произведения'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание вашего произведения.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Год выпуска', max_digits=4, null=True, verbose_name='Год выпуска'),
        ),
    ]
