# Generated by Django 3.0.5 on 2021-06-15 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210615_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('review_id', models.ForeignKey(help_text='Отзыв на котоорый сделан комментарий.', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.Review', verbose_name='отзыв')),
                ('title_id', models.ForeignKey(help_text='Произведение интелектуальное.', on_delete=django.db.models.deletion.CASCADE, related_name='title', to='api.Title', verbose_name='произвидение')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('title_id', 'review_id'), name='unique user_following'),
        ),
    ]
