# Generated by Django 3.0.5 on 2021-06-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210615_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',), 'verbose_name': 'comment', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique user_following',
        ),
    ]
