# Generated by Django 3.0.5 on 2021-06-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210615_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title_id',
        ),
    ]
