# Generated by Django 3.0.5 on 2021-06-24 10:00

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210624_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10, 'Не найден объект оценки [ 1 .. 10 ]')]),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Год выпуска', null=True, validators=[django.core.validators.MinValueValidator(1800), api.models.max_value_current_year], verbose_name='Год выпуска'),
        ),
    ]
