POST  http://127.0.0.1:8000/api/v1/auth/email/
content-type: application/json

{"email": "test@gmail.com"}

###

GET http://127.0.0.1:8000/api/v1/users/
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI0NDc2NjE5LCJqdGkiOiJlZDcxODVkYTk4ZTg0ZjFkYWY0NGFhYTg3YjIwNjIxOCIsInVzZXJfaWQiOjF9.vGrrnFfso8wS9EUTpR_tmrOTYbTNeN2wOXNcGqDzn5E
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI0NDkzMzA4LCJqdGkiOiJlYzA2ZDFlNzA4MmQ0NzMyODRhMTBiNjVmMmZmYzRjYiIsInVzZXJfaWQiOjN9.6lAGv4HdQCw8BdO-icDXUagGCjMdK8zGPpfMs4doCKU

# {"username": "test", "email": "test@gmail.com", "confirmation_code": ""}
###

POST http://127.0.0.1:8000/api/v1/categories/
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI0NDc2NjE5LCJqdGkiOiJlZDcxODVkYTk4ZTg0ZjFkYWY0NGFhYTg3YjIwNjIxOCIsInVzZXJfaWQiOjF9.vGrrnFfso8wS9EUTpR_tmrOTYbTNeN2wOXNcGqDzn5E
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI0NDkyODQ5LCJqdGkiOiI1NjA4MzY3NTM2MzA0OTdkOTkzZTE2ZmJmNjI0NDliNyIsInVzZXJfaWQiOjN9.JdSheAfoz75exXQkn5Ojdhxi2DybSvHmIpWhcI6EBQo

{"name": "Music3", "slug": "music3"}
###


POST http://127.0.0.1:8000/api/v1/auth/token/
content-type: application/json

{"email": "test@gmail.com",
"confirmation_code": "SWlPnjk4WuVT"}

###

POST http://127.0.0.1:8000/api/v1/users/
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI0NDc2NjE5LCJqdGkiOiJlZDcxODVkYTk4ZTg0ZjFkYWY0NGFhYTg3YjIwNjIxOCIsInVzZXJfaWQiOjF9.vGrrnFfso8wS9EUTpR_tmrOTYbTNeN2wOXNcGqDzn5E

{"username": "test", "email": "test@gmail.com", "confirmation_code": "", "role":  "user"}

###

GET http://127.0.0.1:8000/api/v1/follow/
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjIyODg1NDA2LCJqdGkiOiI5ODhhOTI0NjM5NGE0MTFhYTkzZTU5Mzc2MWVhNTU2NCIsInVzZXJfaWQiOjF9.jApjcirZhD-C3yC_jaEhiIOnpHX--OfeYuM1_BIPdO4



###


POST http://127.0.0.1:8000/api/v1/follow/
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjIyODg1NDA2LCJqdGkiOiI5ODhhOTI0NjM5NGE0MTFhYTkzZTU5Mzc2MWVhNTU2NCIsInVzZXJfaWQiOjF9.jApjcirZhD-C3yC_jaEhiIOnpHX--OfeYuM1_BIPdO4

{}

###

POST  http://127.0.0.1:8000/api/v1/posts/
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjIxOTc1NDYxLCJqdGkiOiI0ZjYzOTQ0N2FkMTE0ZjBjOTkwMmI0MWEzNGZlMjExMyIsInVzZXJfaWQiOjF9.qBNH2OBHuqEXaONM9afaHqRY01Wy_nf5MtgW-Ze8Iok

{
"text": "New Post 1"
}


"refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTYyMzkxMTM2NCwianRpIjoiZGY2Mzc1ZWE4NjBkNDAwODhlOTU2ZTgwMDZhODQxMGUiLCJ1c2VyX2lkIjoxfQ.9irAuSs7RPzT3pHzZ7SewTSTI59nyxRw0CXbnPYNa6A",
  "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjIzODI1MjY0LCJqdGkiOiI3NjRlMGMwMmViMDU0M2M2YjYxNmY1OTdlNmJiM2FlOCIsInVzZXJfaWQiOjF9.mzoFEsow3wUMLjwxRhYdzurYB0rfnSIAugs_fqDXx8k"
}